quiz/web/contacts/urls.py
from django.urls import path
from . import views


app_name = 'contacts'

urlpatterns = [
    path('', views.ContactList.as_view(), name='list'),
    path('<int:pk>/', views.ContactDetail.as_view(), name='detail'),
    path('create', views.ContactCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.ContactUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.ContactDelete.as_view(), name='delete'),
]

quiz/web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda req: redirect('/contacts/')),
    path('contacts/', include('contacts.urls')),
]

quiz/web/contacts/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=50)
    line_id = models.CharField(max_length=10, null=False)

    def get_absolute_url(self):
        return reverse('contacts:detail',  kwargs={'pk': self.pk})

quiz/web/contacts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Contact

# Create your views here.

class ContactList(ListView): 
    model = Contact
class ContactDetail(DetailView): 
    model = Contact
class ContactCreate(CreateView):
    fields='__all__'
    model = Contact
class ContactUpdate(UpdateView): 
    fields='__all__'
    model = Contact        
class ContactDelete(DeleteView): 
    model = Contact    
    success_url = reverse_lazy('contacts:list')

quiz/web/contacts/templates/contacts/contact_delete.html
<h1>Contact Delete?</h1>
<form  method="post">
{% csrf_token %}
Are you sure you want to delete this contact?
<input  type="submit"  value="Submit"  />
</form>

quiz/web/contacts/templates/contacts/contact_detail.html
<h1>Contact Details</h1>
<p>Name: {{object.name}}</p>
<p>Email: {{object.email}}</p>
<p>Address: {{object.address}}</p>
<p>Phone: {{object.phone}}</p>

quiz/web/contacts/templates/contacts/contact_form.html
<h1>Contact Update</h1>
<form  method="post">
{% csrf_token %}
{{ form.as_p }}
<input  type="submit"  value="Submit"  />
</form>

quiz/web/contacts/templates/contacts/contact_list.html
<h1>Contacts</h1>
<table>
<thead>
<tr>
<th>Name</th>
<th>Email</th>
<th>Address</th>
<th>Phone</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
{% for contact in object_list %}
<tr>
<td>{{ contact.name }}</td>
<td>{{ contact.email }}</td>
<td>{{ contact.address }}</td>
<td>
<a  href="{% url "contacts:detail"  contact.id  %}">details</a>
<a  href="{% url "contacts:update"  contact.id  %}">edit</a>
<a  href="{% url "contacts:delete"  contact.id  %}">delete</a>
</td>
</tr>
{% endfor %}
</tbody>
</table>